# 13 June

## Numeric python

In [2]:
import numpy as np

In [3]:
arr = np.array([12, 23, 45,56,32])

In [4]:
arr

array([12, 23, 45, 56, 32])

In [5]:
print(arr)

[12 23 45 56 32]


In [8]:
type(arr)

numpy.ndarray

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr = np.array([12, 23, 45,56,32,66.22, 'pune'])

In [8]:
arr.dtype # or we also write only arr for finding data type

dtype('<U32')

In [11]:
%%timeit  # to find how much time is taken for run this cell
arr = np.array([12, 23, 45,56,32,66.22, 'pune'])

3.26 µs ± 475 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
arr[3]

'56'

In [13]:
arr[-1]

'pune'

In [14]:
arr.shape

(7,)

In [15]:
arr = np.array([12, 23, 45,56,32])

In [16]:
arr*2

array([ 24,  46,  90, 112,  64])

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
np.arange(2,5,7)

array([2])

In [20]:
np.arange(1.5,5.5)

array([1.5, 2.5, 3.5, 4.5])

In [21]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 2d array

In [28]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])

In [29]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
arr1.shape

(4, 3)

In [31]:
arr1.ndim

2

In [32]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
arr1.shape

(4, 3)

In [36]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [39]:
arr1.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [40]:
arr1.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [43]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [44]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
arr1[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
arr

array([12, 23, 45, 56, 32])

In [48]:
arr.mean()

33.6

In [49]:
arr.min()

12

In [50]:
arr.max()

56

In [51]:
arr = np.array([1,3,5,6,3,3,1,7])

In [52]:
np.unique(arr)

array([1, 3, 5, 6, 7])

In [54]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.linalg.det(arr1)

-9.51619735392994e-16

In [56]:
np.linalg.inv(arr1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [58]:
arr2 = np.array([[1,2,3],[4,5,6],[7,12,11]])
arr2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 12, 11]])

In [59]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 96, 99]])